# .github/workflows/test01.yaml
name: test_ci1
on:
  workflow_dispatch:  
jobs:
  test01:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
        with:
          repository: jptd/JPT-TEST-FRAUDWALL
          token: ${{ secrets.GH_PAT }}
     #Setup Python   
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Install Chrome Browser
        run: sudo apt-get install -y chromium-browser
      - name: Install the necessary packages
        run: pip install -r requirements.txt
      - name: Run the PyTest script
        run: pytest --alluredir=allure-results tests/ui/auth
        env:
          DEFAULT_WAIT_TIME: 30
          ELEMENT_WAIT_TIME: 15
          FW_URL: 'https://console.aml-defender.com'
          SMART_RULES_FIELDS_JSON: 'tests/test_data/smart_rules/smart_rule_temp.json'
          GROUPS_FIELDS_JSON: 'tests/test_data/groups/groups_fields.json'
          VIPLISTS_FIELDS_JSON: 'tests/test_data/viplists/viplists_fields.json'
          WATCHLISTS_FIELDS_JSON: 'tests/test_data/watchlists/watchlists_fields.json'
      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GH_PAT }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
      