# .github/workflows/test01.yaml
name: test_ci1
on:
  workflow_dispatch:  
jobs:
  test01:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
        with:
          repository: jptd/JPT-TEST-FRAUDWALL
          token: ${{ secrets.GH_PAT }}
     #Setup Python   
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Install Chrome Browser
        run: sudo apt-get install -y chromium-browser
      - name: Install the necessary packages
        run: pip install -r requirements.txt
      - name: Run the PytTest script
        run: pytest -sv tests/ui/auth
        env:
          DEFAULT_WAIT_TIME: 60
          ELEMENT_WAIT_TIME: 45
          FW_URL: 'https://console.aml-defender.com'
          SMART_RULES_FIELDS_JSON: 'tests/test_data/smart_rules/smart_rule_temp.json'
          GROUPS_FIELDS_JSON: 'tests/test_data/groups/groups_fields.json'
          VIPLISTS_FIELDS_JSON: 'tests/test_data/viplists/viplists_fields.json'
          WATCHLISTS_FIELDS_JSON: 'tests/test_data/watchlists/watchlists_fields.json'